version: "3.9"
services:
  dictionary-backend:
    build: ./backend
    container_name: dictionary-backend
    command: sh -c "cd backend && yarn install && yarn dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  dictionary-frontend:
    build: ./frontend
    container_name: dictionary-frontend
    command: sh -c "cd frontend && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    ports:
      - "3001:3001"
    depends_on:
      - dictionary-backend

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata:
    external: true


